// SPDX-License-Identifier: BSD-3-Clause

import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const projectRoot = resolve(import.meta.dirname, '..');
const provenance = JSON.parse(await readFile(resolve(projectRoot, 'compat/mdd-provenance.json'), 'utf8'));
const inputPath = resolveInputPath();
const outputPath = resolve(projectRoot, 'src/generated/mdd.js');
const input = await readFile(inputPath);
const sourceSha256 = createHash('sha256').update(input).digest('hex');
if (sourceSha256 !== provenance.source.sha256) {
  throw new Error(
    `MDD source checksum mismatch: expected ${provenance.source.sha256}, got ${sourceSha256}`
  );
}
const source = input.toString('utf8').replace(/\/\/.*$/gmu, '');
const table = source.match(/s_MDD_Table\[\]\s*=\s*\{([\s\S]*?)\n\};/u)?.[1];
if (!table) throw new Error(`Could not find s_MDD_Table in ${inputPath}`);

const entryPattern = /\{\s*\{([^{}]+)\}\s*,\s*\{([^{}]+)\}\s*,\s*(true|false)\s*,\s*"([^"]+)"\s*\}/gu;
const entries = [];
for (const match of table.matchAll(entryPattern)) {
  const ul = parseBytes(match[1], 16, 'UL', entries.length);
  const tag = parseBytes(match[2], 2, 'tag', entries.length);
  entries.push({
    id: entries.length,
    name: match[4],
    ulHex: hex(ul),
    tag: (tag[0] << 8) | tag[1],
    optional: match[3] === 'true'
  });
}

if (entries.length !== provenance.generated.entryCount) {
  throw new Error(`Parsed ${entries.length} MDD entries, expected ${provenance.generated.entryCount}`);
}
const generated = `// SPDX-License-Identifier: BSD-3-Clause\n` +
  `// Generated by scripts/generate-mdd.mjs from AS-DCP ${provenance.source.version} src/MDD.cpp.\n` +
  `// Entries represent standardized metadata; see NOTICE and LICENSE-ASDCP.\n` +
  `// Do not edit manually.\n\n` +
  `export const MDD_ENTRIES = ${JSON.stringify(entries, null, 2)};\n`;

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error('Generated MDD dictionary is stale; run npm run generate:mdd');
  }
  console.log(`MDD dictionary matches ${entries.length} upstream entries`);
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated);
  console.log(`Generated ${entries.length} MDD entries in ${outputPath}`);
}

function resolveInputPath() {
  if (process.env.ASDCP_MDD_CPP) return resolve(process.env.ASDCP_MDD_CPP);
  if (process.env.ASDCP_SOURCE_DIR) {
    return resolve(process.env.ASDCP_SOURCE_DIR, provenance.source.path);
  }
  throw new Error(
    'MDD regeneration requires ASDCP_SOURCE_DIR or ASDCP_MDD_CPP; normal checks do not require upstream source'
  );
}

function parseBytes(text, length, label, index) {
  const values = text.split(',')
    .map((token) => token.trim())
    .filter(Boolean)
    .map((token) => {
      if (!/^(?:0x[0-9a-f]{1,2}|\d{1,3})$/iu.test(token)) {
        throw new Error(`MDD entry ${index} ${label} contains invalid byte ${JSON.stringify(token)}`);
      }
      const value = Number.parseInt(token, token.toLowerCase().startsWith('0x') ? 16 : 10);
      if (value > 0xff) throw new Error(`MDD entry ${index} ${label} byte exceeds 255: ${token}`);
      return value;
    });
  if (values.length === 1 && values[0] === 0) return Array(length).fill(0);
  if (values.length !== length) {
    throw new Error(`MDD entry ${index} ${label} has ${values.length} bytes, expected ${length}`);
  }
  return values;
}

function hex(bytes) {
  return bytes.map((byte) => byte.toString(16).padStart(2, '0')).join('');
}
